name = "OptimalTransportNetworks"
uuid = "e2b46e68-897f-4e4e-ba36-a93c9789fd96"
authors = ["Sebastian Krantz <sebastian.krantz@graduateinstitute.ch>"]
version = "0.2.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.8.5, 1.9"
Ipopt = "1.4.0, 2"
JuMP = "1.20.0, 2"
LinearAlgebra = "1.0.0, 2"
NearestNeighbors = "0.4.10, 1"
Plots = "1.19.0, 2"
Dierckx = "0.5.0, 1"
Random = "1.0.0, 2"
SparseArrays = "1.0.0, 2"
StaticArrays = "1.1.0, 2"
Statistics = "1.0.0, 2"





